// Code generated by ent, DO NOT EDIT.

package user

import (
	"golang-gql/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.User {
	return predicate.User(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.User {
	return predicate.User(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.User {
	return predicate.User(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.User {
	return predicate.User(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.User {
	return predicate.User(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldName, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEmail, v))
}

// Dob applies equality check predicate on the "dob" field. It's identical to DobEQ.
func Dob(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldDob, v))
}

// PhNo applies equality check predicate on the "ph_no" field. It's identical to PhNoEQ.
func PhNo(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPhNo, v))
}

// Department applies equality check predicate on the "department" field. It's identical to DepartmentEQ.
func Department(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldDepartment, v))
}

// Semester applies equality check predicate on the "semester" field. It's identical to SemesterEQ.
func Semester(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldSemester, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldName, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldEmail, v))
}

// DobEQ applies the EQ predicate on the "dob" field.
func DobEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldDob, v))
}

// DobNEQ applies the NEQ predicate on the "dob" field.
func DobNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldDob, v))
}

// DobIn applies the In predicate on the "dob" field.
func DobIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldDob, vs...))
}

// DobNotIn applies the NotIn predicate on the "dob" field.
func DobNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldDob, vs...))
}

// DobGT applies the GT predicate on the "dob" field.
func DobGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldDob, v))
}

// DobGTE applies the GTE predicate on the "dob" field.
func DobGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldDob, v))
}

// DobLT applies the LT predicate on the "dob" field.
func DobLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldDob, v))
}

// DobLTE applies the LTE predicate on the "dob" field.
func DobLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldDob, v))
}

// DobContains applies the Contains predicate on the "dob" field.
func DobContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldDob, v))
}

// DobHasPrefix applies the HasPrefix predicate on the "dob" field.
func DobHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldDob, v))
}

// DobHasSuffix applies the HasSuffix predicate on the "dob" field.
func DobHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldDob, v))
}

// DobEqualFold applies the EqualFold predicate on the "dob" field.
func DobEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldDob, v))
}

// DobContainsFold applies the ContainsFold predicate on the "dob" field.
func DobContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldDob, v))
}

// PhNoEQ applies the EQ predicate on the "ph_no" field.
func PhNoEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPhNo, v))
}

// PhNoNEQ applies the NEQ predicate on the "ph_no" field.
func PhNoNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldPhNo, v))
}

// PhNoIn applies the In predicate on the "ph_no" field.
func PhNoIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldPhNo, vs...))
}

// PhNoNotIn applies the NotIn predicate on the "ph_no" field.
func PhNoNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldPhNo, vs...))
}

// PhNoGT applies the GT predicate on the "ph_no" field.
func PhNoGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldPhNo, v))
}

// PhNoGTE applies the GTE predicate on the "ph_no" field.
func PhNoGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldPhNo, v))
}

// PhNoLT applies the LT predicate on the "ph_no" field.
func PhNoLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldPhNo, v))
}

// PhNoLTE applies the LTE predicate on the "ph_no" field.
func PhNoLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldPhNo, v))
}

// PhNoContains applies the Contains predicate on the "ph_no" field.
func PhNoContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldPhNo, v))
}

// PhNoHasPrefix applies the HasPrefix predicate on the "ph_no" field.
func PhNoHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldPhNo, v))
}

// PhNoHasSuffix applies the HasSuffix predicate on the "ph_no" field.
func PhNoHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldPhNo, v))
}

// PhNoEqualFold applies the EqualFold predicate on the "ph_no" field.
func PhNoEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldPhNo, v))
}

// PhNoContainsFold applies the ContainsFold predicate on the "ph_no" field.
func PhNoContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldPhNo, v))
}

// DepartmentEQ applies the EQ predicate on the "department" field.
func DepartmentEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldDepartment, v))
}

// DepartmentNEQ applies the NEQ predicate on the "department" field.
func DepartmentNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldDepartment, v))
}

// DepartmentIn applies the In predicate on the "department" field.
func DepartmentIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldDepartment, vs...))
}

// DepartmentNotIn applies the NotIn predicate on the "department" field.
func DepartmentNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldDepartment, vs...))
}

// DepartmentGT applies the GT predicate on the "department" field.
func DepartmentGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldDepartment, v))
}

// DepartmentGTE applies the GTE predicate on the "department" field.
func DepartmentGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldDepartment, v))
}

// DepartmentLT applies the LT predicate on the "department" field.
func DepartmentLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldDepartment, v))
}

// DepartmentLTE applies the LTE predicate on the "department" field.
func DepartmentLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldDepartment, v))
}

// DepartmentContains applies the Contains predicate on the "department" field.
func DepartmentContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldDepartment, v))
}

// DepartmentHasPrefix applies the HasPrefix predicate on the "department" field.
func DepartmentHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldDepartment, v))
}

// DepartmentHasSuffix applies the HasSuffix predicate on the "department" field.
func DepartmentHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldDepartment, v))
}

// DepartmentEqualFold applies the EqualFold predicate on the "department" field.
func DepartmentEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldDepartment, v))
}

// DepartmentContainsFold applies the ContainsFold predicate on the "department" field.
func DepartmentContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldDepartment, v))
}

// SemesterEQ applies the EQ predicate on the "semester" field.
func SemesterEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldSemester, v))
}

// SemesterNEQ applies the NEQ predicate on the "semester" field.
func SemesterNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldSemester, v))
}

// SemesterIn applies the In predicate on the "semester" field.
func SemesterIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldSemester, vs...))
}

// SemesterNotIn applies the NotIn predicate on the "semester" field.
func SemesterNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldSemester, vs...))
}

// SemesterGT applies the GT predicate on the "semester" field.
func SemesterGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldSemester, v))
}

// SemesterGTE applies the GTE predicate on the "semester" field.
func SemesterGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldSemester, v))
}

// SemesterLT applies the LT predicate on the "semester" field.
func SemesterLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldSemester, v))
}

// SemesterLTE applies the LTE predicate on the "semester" field.
func SemesterLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldSemester, v))
}

// SemesterContains applies the Contains predicate on the "semester" field.
func SemesterContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldSemester, v))
}

// SemesterHasPrefix applies the HasPrefix predicate on the "semester" field.
func SemesterHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldSemester, v))
}

// SemesterHasSuffix applies the HasSuffix predicate on the "semester" field.
func SemesterHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldSemester, v))
}

// SemesterEqualFold applies the EqualFold predicate on the "semester" field.
func SemesterEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldSemester, v))
}

// SemesterContainsFold applies the ContainsFold predicate on the "semester" field.
func SemesterContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldSemester, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.User) predicate.User {
	return predicate.User(sql.NotPredicates(p))
}
