// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	Email      string `json:"email"`
	Dob        string `json:"dob"`
	PhNo       string `json:"phNo"`
	Department string `json:"department"`
	Semester   string `json:"semester"`
}
