package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"
	"golang-gql/graph/model"
	"strconv"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, name string, email string, dob string, phNo string, department string, semester string) (*model.User, error) {
	user, err := r.Client.User.
		Create().
		SetName(name).
		SetEmail(email).
		SetDob(dob).
		SetPhNo(phNo).
		SetDepartment(department).
		SetSemester(semester).
		Save(ctx)

	if err != nil {
		return nil, err
	}

	return &model.User{
		ID:         strconv.Itoa(user.ID),
		Name:       user.Name,
		Email:      user.Email,
		Dob:        user.Dob,
		PhNo:       user.PhNo,
		Department: user.Department,
		Semester:   user.Semester,
	}, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, name string, email string, dob string, phNo string, department string, semester string) (*model.User, error) {
	userID, err := strconv.Atoi(id)
	if err != nil {
		return nil, err
	}

	user, err := r.Client.User.
		UpdateOneID(userID).
		SetName(name).
		SetEmail(email).
		SetDob(dob).
		SetPhNo(phNo).
		SetDepartment(department).
		SetSemester(semester).
		Save(ctx)

	if err != nil {
		return nil, err
	}

	return &model.User{
		ID:         strconv.Itoa(user.ID),
		Name:       user.Name,
		Email:      user.Email,
		Dob:        user.Dob,
		PhNo:       user.PhNo,
		Department: user.Department,
		Semester:   user.Semester,
	}, nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (*model.User, error) {
	userID, err := strconv.Atoi(id)
	if err != nil {
		return nil, err
	}

	user, err := r.Client.User.Get(ctx, userID)
	if err != nil {
		return nil, err
	}

	err = r.Client.User.DeleteOneID(userID).Exec(ctx)
	if err != nil {
		return nil, err
	}

	return &model.User{
		ID:         strconv.Itoa(user.ID),
		Name:       user.Name,
		Email:      user.Email,
		Dob:        user.Dob,
		PhNo:       user.PhNo,
		Department: user.Department,
		Semester:   user.Semester,
	}, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context) ([]*model.User, error) {
	users, err := r.Client.User.
		Query().
		All(ctx)

	if err != nil {
		return nil, err
	}

	var results []*model.User
	for _, u := range users {
		results = append(results, &model.User{
			ID:         strconv.Itoa(u.ID),
			Name:       u.Name,
			Email:      u.Email,
			Dob:        u.Dob,
			PhNo:       u.PhNo,
			Department: u.Department,
			Semester:   u.Semester,
		})
	}
	return results, nil
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, id string) (*model.User, error) {
	userID, err := strconv.Atoi(id)
	if err != nil {
		return nil, err
	}

	user, err := r.Client.User.Get(ctx, userID)
	if err != nil {
		return nil, err
	}

	return &model.User{
		ID:         strconv.Itoa(user.ID),
		Name:       user.Name,
		Email:      user.Email,
		Dob:        user.Dob,
		PhNo:       user.PhNo,
		Department: user.Department,
		Semester:   user.Semester,
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
