# GraphQL schema example
#
# https://gqlgen.com/getting-started/

type User {
  id: ID!
  name: String!
  email: String!
  dob: String!
  phNo: String!
  department: String!
  semester: String!
}

type Query {
  user: [User!]!
  getUser(id: ID!): User
}

type Mutation {
  createUser(name: String!, email: String!, dob: String!, phNo: String!, department: String!, semester: String!): User!
  updateUser(id: ID!, name: String!, email: String!, dob: String!, phNo: String!, department: String!, semester: String!): User!
  deleteUser(id: ID!): User!
}
